// categoria
export const SET_CATEGORIAS = 'CATEGORIA/SET_CATEGORIAS'
export const ADD_CATEGORIA = 'CATEGORIA/ADD_CATEGORIA'
export const REMOVE_CATEGORIA = 'CATEGORIA/REMOVE_CATEGORIA'
export const UPDATE_CATEGORIA = 'CATEGORIA/UPDATE_CATEGORIA'
