export const SET_RECEITAS = 'RECEITA/SET_RECEITAS'
export const ADD_RECEITA = 'RECEITA/ADD_RECEITA'
export const UPDATE_RECEITA = 'RECEITA/UPDATE_RECEITA'
export const REMOVE_RECEITA = 'RECEITA/REMOVE_RECEITA'
